} catch (IOException | ArrayIndexOutOfBoundsException  io) {
    System.out.println("Outer catch exception block starts here....");