} catch (ACustomRuntimeException are) {
 
    System.out.println("In the catch clause for" +
            " ACustomRuntimeException in main(): " +
            are);
 
}